openapi: 3.0.3
info:
  title: Biblioteca Code Cafe API
  version: 0.0.0

paths:
  /authors:
    $ref: "./paths/get-all-authors.path.yaml"
  /authors/id/{id}:
    $ref: "./paths/get-author-by-id.path.yaml"
  /authors/name/{name}:
    $ref: "./paths/get-author-by-name.path.yaml"
  /authors/create:
    $ref: "./paths/create-author.path.yaml"

  /publishers:
    $ref: "./paths/get-all-publishers.path.yaml"
  /publishers/{id}:
    $ref: "./paths/get-publisher-by-id.path.yaml"
  /publishers/name/{name}:
    $ref: "./paths/get-publisher-by-name.path.yaml"
  /publishers/create:
    $ref: "./paths/create-publisher.path.yaml"
  /publishers/update/id/{id}:
    $ref: "./paths/update-publisher.path.yaml"
  /publishers/delete/id/{id}:
    $ref: "./paths/delete-publisher.path.yaml"


  /auth/register:
    $ref: "./paths/register.path.yaml"
  /auth/login:
    $ref: "./paths/login.path.yaml"

  /categories:
    $ref: "./paths/get-all-categories.path.yaml"
  /categories/id/{id}:
    $ref: "./paths/get-category-by-id.path.yaml"
  /categories/name/{name}:
    $ref: "./paths/get-category-by-name.path.yaml"
  /categories/create:
    $ref: "./paths/create-category.path.yaml"
  /categories/update/id/{id}:
    $ref: "./paths/update-category.path.yaml"
  /categories/delete/id/{id}:
    $ref: "./paths/delete-category.path.yaml"

  /books:
    $ref: "./paths/get-all-books.path.yaml"
  /books/title/{name}:
    $ref: "./paths/get-books-by-title.path.yaml"
  /books/isbn/{id}:
    $ref: "./paths/get-book-by-isbn.path.yaml"
  /books/create:
    $ref: "./paths/create-book.path.yaml"
  /books/update/isbn/{id}:
    $ref: "./paths/update-book.path.yaml"
  /books/{isbn}/files:
    $ref: "./paths/update-book-files.path.yaml"
  /books/delete/isbn/{id}:
    $ref: "./paths/delete-book.path.yaml"


  /users/name/{name}:
    $ref: "./paths/get-user-by-name.path.yaml"
  /users/id/{id}:
    $ref: "./paths/get-user-by-id.path.yaml"
  /users:
    $ref: "./paths/get-all-users.path.yaml"
    
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      $ref: "./components/error-response.component.yaml#/ErrorResponse"
    DataResponse:
      $ref: "./components/data-response.component.yaml#/DataResponse"
    Authorization:
      $ref: "./components/authorization.component.yaml#/Authorization"

    Author:
      $ref: "./components/author.component.yaml#/Author"
    AuthorOutDto:
      $ref: "./components/author-out-dto.component.yaml#/AuthorOutDto"

    Publisher:
      $ref: "./components/publisher.component.yaml#/Publisher"
    PublisherOutDTO:
      $ref: "./components/publisher-out-dto.component.yaml#/PublisherOutDTO"
    CreatePublisherDto:
      $ref: "./components/create-publisher-dto.component.yaml#/CreatePublisherDto"


    RegisterInDTO:
      $ref: "./components/register-in-dto.component.yaml#/RegisterInDTO"
    LoginInDTO:
      $ref: "./components/login-in-dto.component.yaml#/LoginInDTO"
    UserOutDTO:
      $ref: "./components/user-out-dto.component.yaml#/UserOutDTO"

    Category:
      $ref: "./components/category.component.yaml#/Category"
    CategoryOutDTO:
      $ref: "./components/category-out-dto.component.yaml#/CategoryOutDTO"
    CreateCategoryDto:
      $ref: "./components/create-category-dto.component.yaml#/CreateCategoryDto"

    BookOutDTO:
      $ref: "./components/book-out-dto.component.yaml#/BookOutDTO"
