openapi: 3.0.3
info:
  title: Biblioteca Code Cafe API
  version: 0.0.0
paths:
  /authors/id/{id}:
    $ref: "./paths/get-author-by-id.path.yaml"
  /authors/name/{name}:
    $ref: "./paths/get-author-by-name.path.yaml"
  /authors:
    $ref: "./paths/get-all-authors.path.yaml"
  /publishers/{id}:
    $ref: "./paths/get-publisher-by-id.path.yaml"
  /publishers/name/{name}:
    $ref: "./paths/get-publisher-by-name.path.yaml"
  /publishers:
    $ref: "./paths/publishers.path.yaml"
components:
  schemas:
    Author:
      $ref: "./components/author.component.yaml#/Author"
    AuthorOutDTO:
      $ref: "./components/author-out-dto.component.yaml#/AuthorOutDTO"
    Publisher:
      $ref: "./components/publisher.component.yaml#/components/schemas/Publisher"
    PublisherOutDTO:
      $ref: "./components/publisher-out-dto.component.yaml#/PublisherOutDTO"
    PublisherInput:
      $ref: "./components/publisher.component.yaml#/components/schemas/PublisherInput"
    PublisherResponse:
      $ref: "./components/publisher.component.yaml#/components/schemas/PublisherResponse"
    PublishersResponse:
      $ref: "./components/publisher.component.yaml#/components/schemas/PublishersResponse"
