openapi: 3.0.3
info:
  title: Biblioteca Code Cafe API — Publishers
  version: 0.0.1
paths:
  /publishers/{id}:
    $ref: "./paths/get-publisher-by-id.path.yaml"
components:
  schemas:
    $ref: "./components/publisher.component.yaml"